### ISSUE TITLE
why so many descriptions are empty?

### ISSUE THREAD

**Issue by zenghsh3** [johnthebrave/nlidb-datasets#1]
There are about 19000 empty descriptions in train.json. But, the paper (Dataset for a Neural Natural Language Interface for Databases) said that use (description, sql) pair to train an attention based seq2seq model. Did the paper only use non-empty descriptions to train the model? @johnthebrave

**Comment by johnthebrave** [comment]
We decided to store separately in the json file the description and the title, as they appeared on the data.stackexchange [0]. For training the model we simply concatenated both fields. 

[0] Example with the original format: http://data.stackexchange.com/stackoverflow/query/6627/top-50-most-prolific-editors

**Comment by zenghsh3** [comment]
Got it. Thanks for your reply.
